openapi: 3.0.0
info:
  title: Go Challenge
  description: Definición de la API del *Go Challenge*.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
    description: Servidor local
paths:
  /api/v1/offices/{ID}:
    get:
      summary: Detalle de una sucursal.
      tags:
        - offices
      parameters:
        - name: ID
          in: path
          required: true
          description: Identificador de la sucursal.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Detalle de la sucursal en formato JSON.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 1
                  address:
                    type: string
                    example: El Salvador 5700 - CABA
                  latitude:
                    type: number
                    format: float32
                    example: -34.582375
                  longitude:
                    type: number
                    format: float32
                    example: -58.436463
        '404':
          description: Sucursal no encontrada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Descripción del error.
  /api/v1/offices:
    post:
      summary: Crea una sucursal.
      tags:
        - offices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  example: El Salvador 5700 - CABA
                latitude:
                  type: number
                  format: float32
                  example: -34.582375
                longitude:
                  type: number
                  format: float32
                  example: -58.436463
      responses:
        '201':
          description: Detalle de la sucursal creada en formato JSON.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 2
                  address:
                    type: string
                    example: El Salvador 5700 - CABA
                  latitude:
                    type: number
                    format: float32
                    example: -34.582375
                  longitude:
                    type: number
                    format: float32
                    example: -58.436463
        '400':
          description: Sucursal no encontrada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Descripción deneral del error.
                  details:
                    type: array
                    description: Listado de detalles del error.
                    items:
                      type: string
  /rpc/v1/searches/officeByProximity:
    get:
      summary: Busca la sucursal más cercana.
      tags:
        - searches
      parameters:
        - name: latitude
          in: query
          required: true
          description: Latitud de búsqueda.
          schema:
            type: number
            format: float32
        - name: longitude
          in: query
          required: true
          description: Longitud de búsqueda.
          schema:
            type: number
            format: float32
      responses:
        '200':
          description: Detalle de la sucursal más cercana y distancia de camino respecto de las coordenadas de búsqueda en formato JSON.
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: number
                    format: float32
                    example: 1200.56
                  office:
                    type: object
                    properties:
                      id:
                        type: integer
                        format: int64
                        example: 2
                      address:
                        type: string
                        example: El Salvador 5700 - CABA
                      latitude:
                        type: number
                        format: float32
                        example: -34.582375
                      longitude:
                        type: number
                        format: float32
                        example: -58.436463
        '400':
          description: Sucursal cercana no encontrada o disponible.
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Descripción deneral del error.
  /rpc/v1/systems/health-checks/database/ping:
    get:
      summary: Health check de la base de datos.
      tags:
        - systems
      responses:
        '200':
          description: Ping exitoso a base de datos en formato plano.
          content:
            text/plain:
              schema:
                type: string
                example: PONG
        '500':
          description: Sucursal no encontrada.
          content:
            text/plain:
              schema:
                type: string
                example: ERROR
